name:                json-sql-query
version:             0.1.0.0
github:              "githubuser/json-sql-query"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/json-sql-query#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- text
- bytestring
- scotty
- wai
- wai-cors
- http-types
- mtl
- transformers
- sqlite-simple
- containers
- vector
- scientific

executables:
  json-sql-query-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-sql-query

library:
  source-dirs: src

tests:
  json-sql-query-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-sql-query
    - hspec